# Generated by Django 5.0.6 on 2024-07-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='friend_email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
    ]
